---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: trevorwhitney/push-apps-ci
    tag: latest
inputs:
- name: built-push-apps
params:
  DOCKER_HOST: "10.150.0.6:4243"
  INTEGRATION_HOST: "10.150.0.6"
  LOG_LEVEL: "debug"
  CF_LOG_LEVEL: "error"
  CF_API:
  CF_USERNAME:
  CF_PASSWORD:
  CF_DOMAIN:
run:
  path: bash
  args:
    - -c
    - |
      #!/bin/bash
      set -ex

      apt-get update
      apt-get install -y python-pip
      pip install docker-compose

      echo "Running Acceptance Tests!"

      pushd built-push-apps
        ./gradlew -g .gradleCache acceptanceTest
      popd
