---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: trevorwhitney/push-apps-ci
    tag: latest
inputs:
- name: built-push-apps
params:
  DOCKER_HOST: "10.150.0.6:4243"
  INTEGRATION_HOST: "10.150.0.6"
  LOG_LEVEL: "debug"
  CF_LOG_LEVEL: "error"
  CF_API: ((cf-api))
  CF_USERNAME: ((cf-username))
  CF_PASSWORD: ((cf-password))
  CF_DOMAIN: ((cf-domain))
run:
  path: bash
  args:
    - -c
    - |
      #!/bin/bash
      set -ex

      echo "Running Acceptance Tests!"

      pushd built-push-apps
        ./gradlew -g .gradleCache acceptanceTest
      popd
