---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-slim
inputs:
- name: push-apps
outputs:
- name: push-apps-jar-output
  path: ""
- name: push-apps-bumped
  path: ""
run:
  path: bash
  args:
    - -c
    - |
      #!/bin/bash
      set -ex

      echo "Getting rsync"
      apt-get update
      apt-get install -y rsync

      pushd push-apps
        ./gradlew bumpPatch

        git add -A
        git commit -m "bump version"

        ./gradlew assemble
      popd

      cp push-apps/applications/cli/build/libs/push-apps-*.jar push-apps-jar-output/

      rsync -a push-apps/ push-apps-bumped
