---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: trevorwhitney/push-apps-ci
    tag: latest
inputs:
- name: push-apps
outputs:
- name: push-apps-jar-output
  path: ""
- name: push-apps-bumped
  path: ""
params:
  S3_ACCESS_KEY: ((pcf-metrics-aws-access-key-id))
  S3_SECRET_KEY: ((pcf-metrics-aws-secret-access-key))
run:
  path: bash
  args:
    - -c
    - |
      #!/bin/bash
      set -ex

      pushd push-apps
        ./gradlew bumpPatch

        git add -A
        git commit -m "bump version"

        ./gradlew assemble
      popd

      cp push-apps/applications/cli/build/libs/push-apps-*.jar push-apps-jar-output/

      rsync -a push-apps/ push-apps-bumped
