---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfmetrics/push-apps-ci
    tag: latest
inputs:
- name: push-apps
outputs:
- name: push-apps-jar-output
  path: ""
- name: push-apps-bumped
  path: ""
run:
  path: bash
  args:
    - -c
    - |
      #!/bin/bash
      set -ex

      pushd push-apps
        ./gradlew bumpPatch

        git add -A
        git commit -m "bump version"

        ./gradlew assemble bintrayUpload
        ./gradlew publishUploadedBintrayArtifacts
        ./gradlew signBintrayArtifacts
        ./gradlew syncArtifactsToMavenCentral
      popd
