---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfmetrics/push-apps-ci
    tag: latest
inputs:
- name: push-apps
outputs:
- name: built-push-apps
run:
  path: bash
  args:
    - -c
    - |
      #!/bin/bash
      set -ex

      echo "Running tests!"
      pushd push-apps
        ./gradlew -g .gradleCache clean build
      popd

      rsync -a push-apps/ built-push-apps/
