---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-slim
inputs:
- name: push-apps
outputs:
- name: built-push-apps
run:
  path: bash
  args:
    - -c
    - |
      #!/bin/bash
      set -ex

      echo "Getting rsync"
      apt-get update
      apt-get install -y rsync

      echo "Running tests!"
      pushd push-apps
        ./gradlew -g .gradleCache clean build
      popd

      rsync -a push-apps/ built-push-apps/
