---
resources:
- name: metrics-app-dev-release
  type: git
  source:
    uri: git@github.com:pivotal-cf/metrics-app-dev-release.git
    branch: release-v1.5
    private_key: ((metrics-git-key))
    submodules: all
- name: push-apps
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/push-apps.git
    branch: master
    private_key: ((push-apps-git-key))
    submodules: all
- name: deployments-metrics
  type: git
  source:
    uri: git@github.com:pivotal-cf/deployments-metrics.git
    private_key: ((metrics-git-key))

- name: push-apps-s3
  type: s3
  source:
    bucket: pcf-metrics
    regexp: pcf-metrics-push-apps/push-apps-(.*).jar
    access_key_id: ((pcf-metrics-aws-access-key-id))
    secret_access_key: ((pcf-metrics-aws-secret-access-key))

jobs:
- name: test-push-apps
  build_logs_to_retain: 25
  serial: true
  plan:
  - aggregate:
    - get: push-apps
      trigger: true
  - task: test
    timeout: 10m
    file: push-apps/ci/tasks/test.yml
  - task: acceptance-test
    attempts: 3
    timeout: 15m
    file: push-apps/ci/tasks/acceptance-test.yml
    params:
      CF_API: ((cf-api))
      CF_USERNAME: ((cf-username))
      CF_PASSWORD: ((cf-password))
      CF_DOMAIN: ((cf-domain))

- name: build-push-apps
  build_logs_to_retain: 25
  serial: true
  plan:
  - aggregate:
    - get: push-apps
      trigger: true
      passed: [ test-push-apps ]
    - get: metrics-app-dev-release
    - get: deployments-metrics
  - task: assemble
    file: push-apps/ci/tasks/assemble.yml
    params:
      S3_ACCESS_KEY: ((pcf-metrics-aws-access-key-id))
      S3_SECRET_KEY: ((pcf-metrics-aws-secret-access-key))
  - put: push-apps-s3
    params:
      file: push-apps-jar-output/*.jar
  - put: push-apps
    params:
      repository: push-apps-bumped
      rebase: true
  - task: upload-blob
    file: push-apps/ci/tasks/upload-blob.yml

  - put: metrics-app-dev-release
    params:
      repository: metrics-app-dev-release-bumped
      rebase: true
