---
resources:
- name: push-apps
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/push-apps.git
    branch: master
    private_key: ((push-apps-git-key))
    submodules: all

jobs:
- name: test-push-apps
  build_logs_to_retain: 25
  serial: true
  plan:
  - aggregate:
    - get: push-apps
      trigger: true
  - task: test
    timeout: 10m
    file: push-apps/ci/tasks/test.yml
  - task: acceptance-test
    attempts: 3
    timeout: 15m
    file: push-apps/ci/tasks/acceptance-test.yml
    params:
      CF_API: ((cf-api))
      CF_USERNAME: ((cf-username))
      CF_PASSWORD: ((cf-password))
      CF_DOMAIN: ((cf-domain))

- name: publish-push-apps
  build_logs_to_retain: 25
  serial: true
  plan:
  - aggregate:
    - get: push-apps
      trigger: true
      passed: [ test-push-apps ]
  - task: publish
    file: push-apps/ci/tasks/publish.yml
    params:
      BINTRAY_USER: ((bintray-user))
      BINTRAY_API_KEY: ((bintray-api-key))
      BINTRAY_GPG_PASSPHRASE: ((bintray-gpg-passphrase))
      MAVEN_CENTRAL_TOKEN_USER: ((maven-central-token-user))
      MAVEN_CENTRAL_TOKEN_PASSWORD: ((maven-central-token-password))

- name: build-docker-images
build_logs_to_retain: 25
serial: true
plan:
- aggregate:
  - get: push-apps
    trigger: false
- task: build-docker
  file: push-apps/ci/tasks/build-docker.yml
  params:
    DOCKER_USERNAME: "((docker-username))"
    DOCKER_PASSWORD: "((docker-password))"
